[[pages]]
path = "Streamlit_apps/Diagnosis_Assistant_streamlit_20230125.py"
name = "Diagnosis_Assistant_streamlit_20230125"
icon = ":house:"

[[pages]]
path = "Streamlit_apps/pages/About.py"
name = "About"
icon = ":books:"

[[pages]]
path = "Streamlit_apps/pages/Contact.py"
name = "Contact"
icon = ":envelope:"