# From https://blog.streamlit.io/secrets-in-sharing-apps/
# Everything in this section will be available as an environment variable 
#db_username = "Jane"
#db_password = "12345qwerty"
openai_api_key = "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"
email_address = "geonosis.lambard@gmail.com"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.   
#[my_cool_secrets]
#things_i_like = ["Streamlit", "Python"]